### ISSUE TITLE
A good development environment and testing framework for Ethereum - Proposal

### ISSUE THREAD

**Issue by fjrojasgarcia** [ethereumbook/ethereumbook#1]
I would like to propose this interesting framework to be mention and might be also documented in the future **Ethereum book**.

**Truffle** is a development environment, testing framework and asset pipeline for Ethereum, aiming to make life as an Ethereum developer easier.

`https://github.com/ConsenSys/truffle`

I would like to contribute if necessary.

**Comment by aantonop** [comment]
I welcome contributions.

I expect that Truffle will be part of the book

**Comment by kitsuphat2528** [comment]
Yes,

**Comment by prahaladbelavadi** [comment]
will there be examples of Open Zeppelin also ? @aantonop @maraoz @gustavoguimaraes

**Comment by stefek99** [comment]
Related #82 #89 (probably many others)

The other day I've spent some time trying to deploy a super simple `Solidity` contract: https://github.com/raineorshine/solidity-by-example/issues/5

State of the ecosystem is like internet in 1993 and tools / frameworks are evolving at a rapid pace...

Chapter about it will be always growing, code samples are likely to be out-of-date by the moment of print.

Potentially an Appendix material?
