### ISSUE TITLE
Scalability

### ISSUE THREAD

**Issue by QwQiao** [ethereumbook/ethereumbook#101]
It's probably worth dedicating a major section on scalability. In particular, 
- Why is scalability critical to Ethereum?
- Why is scalability difficult for Ethereum, probably more difficult than it is for Bitcoin?
- A description of the upcoming scalability solutions, namely, PoS, sharding, plasma, raiden, etc.

A challenge is to write something timeless. Since the R&D teams seem to move very fast with scalability solutions, it's potentially hard for the book to be up to date with the latest developments.

**Comment by qiaowang26** [comment]
A challenge is to write something timeless. Since the R&D teams seem to move very fast with scalability solutions, it's potentially hard for the book to be up to date with the latest developments.

**Comment by ltfschoen** [comment]
Here's a link to Vitalik's Ethereum Sharding Research Compendium: http://notes.ethereum.org/s/BJc_eGVFM

Here are some Trello cards I've created to summarise my understanding of Sharding: 
* Trade-Off between Decentralisation vs Scalability vs Security: https://trello.com/c/a8g29lkT/155-trade-off-between-decentralisation-vs-scalability-vs-security
* Summary of the Sharding Specification: https://trello.com/c/0GsZGEHp/154-sharding-specificaton-summary
* Sharding Explicit vs Implicit Finality: https://trello.com/c/zxbFkJu0/157-sharding-with-explicit-finality
* Stateless Clients and Explicity Finality: https://trello.com/c/KwVJQPl8/158-stateless-clients-and-explicit-finality

My favourite resources is the Ethereum Research chat forum which covers all things scalability: https://ethresear.ch/

**Comment by SylTi** [comment]
I think this section should also talk about states channels.

Generalized States Channels
https://github.com/ledgerlabs/state-channels/wiki
exemple implementation (WIP)
https://github.com/SpankChain/general-state-channels

Single Usage State channel example:
https://github.com/Magicking/protochannel/blob/master/contracts/tictactoe.sol

**Comment by ltfschoen** [comment]
Here's a list of key Sharding resources. I'm currently trying to help contribute to Diamond Drops (sharding implementation in Rust):
https://github.com/ethereum/wiki/wiki/Sharding-introduction-and-implementations

**Comment by MorganGR** [comment]
Don't forget the scaling issues for charitable platforms as well as the cost of executing smart contracts when a DApp(Donation Application) is used. (See Giveth.io, Griff Green, ScalingNOW and of course Seedom.io)

**Comment by SylTi** [comment]
https://medium.com/l4-media/making-sense-of-ethereums-layer-2-scaling-solutions-state-channels-plasma-and-truebit-22cb40dcc2f4 A good blog post on this very same subject.

**Comment by SylTi** [comment]
Perun 
https://ethresear.ch/t/perun-virtual-payment-and-state-channel-networks/1685

**Comment by lrettig** [comment]
I can contribute to this section as well. I've done quite a bit of research on the state of scaling and have written about it as well.
