### ISSUE TITLE
Difference between metamask and ethereum provider

### ISSUE THREAD

**Issue by mario335** [ethereumbook/ethereumbook#1013]
I found this image online but I can't tell the difference between metamask and an Ethereum provider. Also doesn't metamask use a provider to connect to the network? I'm confused
![image](https://user-images.githubusercontent.com/76747917/107222177-e3487980-6a14-11eb-82ee-3efa211e7056.png)
What are the differences? What does it mean to choose one or the other in terms of ether and account management?

**Comment by wbnns** [comment]
@mario335 

Hello, in this context it's referring to an alternative Web3 provider. 

> Also doesn't metamask use a provider to connect to the network?

Yes, [Infura](https://infura.io/).
