### ISSUE TITLE
Hardback and paperback books released on March 2021

### ISSUE THREAD

**Issue by tgeorgiop** [ethereumbook/ethereumbook#1018]
Hello, are the hardback and paperback books released this month the 2nd editions of the book?

**Comment by wbnns** [comment]
@tgeorgiop 

Hello, no, the second edition is still being worked on.

**Comment by baermathias** [comment]
@wbnns @aantonop when is v2 expected to be released/printed? Is there any timeline/roadmap?

**Comment by tgeorgiop** [comment]
Any news about the v2 books?

**Comment by baermathias** [comment]
@tgeorgiop there is a new/open issue for this https://github.com/ethereumbook/ethereumbook/issues/1102
