### ISSUE TITLE
Suggestion of list of known Ethereum network ids

### ISSUE THREAD

**Issue by fjrojasgarcia** [ethereumbook/ethereumbook#110]
In order to offer to new programmers information grouped of **currenty used Ethereum networks ids**, I suggest the following list. Please add your corrections.

**0: Olympic**; Ethereum public pre-release testnet
**1: Frontier**; Homestead, Metropolis, the Ethereum public main network
**1: Classic**; The (un)forked public Ethereum Classic main network, chain ID 61
**1: Expanse**; An alternative Ethereum implementation, chain ID 2
**2: Morden**; The public Ethereum testnet, now Ethereum Classic testnet
**3: Ropsten**; The public cross-client Ethereum testnet
**4: Rinkeby**: The public Geth Ethereum testnet
**42: Kovan**; The public Parity Ethereum testnet
**77: Sokol**; The public POA testnet
**99: POA**; The public Proof of Authority Ethereum network
**7762959: Musicoin**; The music blockchain

**Comment by aantonop** [comment]
I agree this is useful

Where is the "network ID"? In the API? In a network message header?

Where would you add this information in the current sections?

**Comment by ChristopherGondek** [comment]
I suggest mentioning that Ropsten is PoW, Rinkeby and Kovan are PoA.
The network ID you have to specify when starting a node. E.g. option --networkid for Geth.

**Comment by fjrojasgarcia** [comment]
I think Andreas is refering **at a protocol level**.
There is a especial message called "**Status**" which send that data (_network ID_) between others.

I'm working deeper in this point and I hope to offer something more accurate and explanatory, surely in the form of **PR**.

**Comment by nicksavers** [comment]
The `networkId` is communicated during the initial **Status**-message in the [ETH Wire protocol](https://github.com/ethereum/wiki/wiki/Ethereum-Wire-Protocol).

Also see [EIP-155](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md).

**Comment by aantonop** [comment]
Incorporated into the DevP2P section

**Comment by H34D** [comment]
i have started a structured list incl. access layer to support auto detection:

https://github.com/ethereum-navigator/atlas/blob/master/atlas.json
