### ISSUE TITLE
not a clear sentence.

### ISSUE THREAD

**Issue by ronytesler** [ethereumbook/ethereumbook#1108]
from https://github.com/ethereumbook/ethereumbook/blob/develop/12dapps.asciidoc#auction_dapp_screen:
"The only functions on the base layer are those that enable a node owner to set information about their own node (specifically the resolver, time to live, or transferring the ownership) and to create owners of new subnodes".

Not clear who the word "their" refers to. The functions? This is the only plural thing here.

**Comment by FranciscoPontes** [comment]
If I understood correctly, "their" refers to "a node owner".

**Comment by ronytesler** [comment]
@FranciscoPontes Ok but that doesn't make sense because "a node owner" is singular, it should be changed to "his" or "node owners".

**Comment by haurog** [comment]
Singular 'they' seems to be widely used in English for at least several hundred years. It has been used to refer to someone of unknown gender. See for example here: https://www.merriam-webster.com/words-at-play/singular-nonbinary-they
