### ISSUE TITLE
Oracles - external data carriers for decentralized apps

### ISSUE THREAD

**Issue by fjrojasgarcia** [ethereumbook/ethereumbook#111]
For me it would be important to mention in the book the **inherent isolation of Ethereum** from the outside world and the importance of defining mechanisms, commonly called **Oracles**, to achieve its interaction with it.

There is already some initiative trying to cover this limitation, such as "http://www.oraclize.it".
They define themselves as the "**data carrier for decentralized apps**".

 Maybe there is something more about it out there.

**Comment by Benudek** [comment]
It seems to me it might be fair to discuss the need to have oracles is also an inherent obstacle for smart contracts to cover without further consideration non digital assets. If a smart contract does sth but the assumptions it has on the world the smart contract might overall be useless or open to manipulation. With digital assets like currencies e.g. Ownership can be proven with cryptography. Owning a car or facts like the weather or who caused an accident, need to come to smart contracts via oracle. This unsolved limits the usecases for smart contracts so far. In my humble opinion :-)

**Comment by dzwiener** [comment]
Auger would be a good token to explore as well since it proposes it will change the way how oracles operate.

**Comment by fjrojasgarcia** [comment]
I agree that the inherent isolation of Ethereum, or any other decentralized system, **is a feature and not a bug**. The thing here for me is more about **the impact of the innovation power** in this field.

As Andreas has helped many of us to understand that the power of innovation transcends unimagined boundaries, I think that probably at this very moment there are a handful of brilliant minds working on this matter and I would not rule out the arrival of some surprising solution.

Perhaps it would be good if the book considered this aspect and that future readers had at least some notion and created their own criteria in this regard.

That's my humble opinion also :-)

**Comment by aantonop** [comment]
Agree, it is important to explain both the security model which depends on isolation, versus the need for Oracles to achieve many real world use cases. 

Where does this fit in the list of topics?

**Comment by aantonop** [comment]
Agree, it is important to explain both the security model which depends on isolation, versus the need for Oracles to achieve many real world use cases. 

Where does this fit in the list of topics?

**Comment by pixboi** [comment]
I think before we can have oracles, we first need immutable, trustless sensors.

**Comment by Pongch** [comment]
I believe this could fit pretty well into DApp section of the book. Since the outlines already explaining off-chain & on-chain Data. We could explore the reasoning behind oracles, then going into its limitations, current & possible implementations etc.

**Comment by timnugent** [comment]
The draft text for oracles is in the contrib directory. One possible issue with putting this within the Dapps section is that oracles are not necessarily Dapps themselves

**Comment by Pongch** [comment]
I see, I wasn't aware the content for oracle is already being written. Come to think of it, Oracles and getting off-chain data as a topic is important enough to deserve its own section in my opinion.

**Comment by aantonop** [comment]
Great work on this topic. See contrib/oracles.asciidoc. It will be included in the first edition
