### ISSUE TITLE
Accept request to translate to French (Canada)

### ISSUE THREAD

**Issue by SerafDosSantos** [ethereumbook/ethereumbook#1120]
Hi, I don't know who's watching the Transifex.com site, but I requested a language translation (French (Canada)) for _Mastering Ethereum_ and no answer.

I'm finishing the translation of _Mastering Bitcoin_ in French (Canada) and I have time to translate _Mastering Ethereum_ in this locale--very soon.

Cheers,
Seraf

**Comment by SerafDosSantos** [comment]
_Mastering Bitcoin_ in French (Canada) is done [bitcoinbook Issue #1000](https://github.com/bitcoinbook/bitcoinbook/issues/1000#issue-1172877370). Now moving on with this edition.

Please accept the locale request French (Canada) on transifex.com as I can only do translation with the terms of the OQLF in Canada (which is a government-sponsored French language registered terminological database recognised in all francophone countries).

Thank you!

**Comment by SerafDosSantos** [comment]
Ahoy @aantonop & repo team! I've completed the _Mastering Ethereum_ book translation to French (Canada).

Cheers!

**Comment by aantonop** [comment]
Nice work Serafim. I hope to publish a French version on my site soon

Feel free to do the same of course, since it might take me a while

**Comment by SerafDosSantos** [comment]
Thanks Andreas! My goal is not necessarily to sell prints, but to make the book content accessible in Africa. There are around 20 french-speaking African countries (~140M people). These books (Mastering BTC & ETH) in french are pure gold for them.

Since these projects are CC-BY-SA, making these available on the web as HTML is a really effective way for them to get access to these books. I run Twitter ads 2-3 weekends per month targeting these countries, no crazy stuff, just a $25 once in a while, but I feel giving lots of value to them.

I'm slowly gathering open educative information in french on blockchains and computing in general and making it freely accessible on [www.maitriser.ca](https://www.maitriser.ca/) ("maitriser.ca" in french can be read like "mastering.this").

Who knows how these blockchain books will inspire Africa... But I'm in some part of it.

---

The repos for both translations are the following :

### Mastering Bitcoin

* Titled on my side _**Maîtriser Bitcoin** : Programmer la chaîne de blocs publique_ (fr_CA) - [github.com/maitriser-ca/LivreMaitriserBitcoin](https://github.com/maitriser-ca/LivreMaitriserBitcoin); **Branch DONE2**
* Online HTML Book : [bitcoin.maitriser.ca](https://bitcoin.maitriser.ca)

### Mastering Ethereum

* Titled on my side _**Maîtriser Ethereum** : Développer des contrats intelligents et des DApps_ (fr_CA) - [github.com/maitriser-ca/LivreMaitriserEthereum](https://github.com/maitriser-ca/LivreMaitriserEthereum); **Branch DONE2**
* Online HTML Book : [ethereum.maitriser.ca](https://ethereum.maitriser.ca)

Thanks again for sharing with us this project!

**Comment by aantonop** [comment]
This is fantastic. Thank you for contributing to the education mission!
