### ISSUE TITLE
Eliminating trust with smart contracts

### ISSUE THREAD

**Issue by pixboi** [ethereumbook/ethereumbook#114]
Whenever I explain smart contracts to my friends, I use the current voting system for example.

When you go to vote:
-You have trust yourself to vote for the right candidate ;)
-You have to trust that nobody sees your vote
-You have to trust that when you slip your number in the tin, that there isn't battery acid which would instantly dissolve it.
-You have to trust that somebody counts it right.

vs. SmartContract which is:
-transparent
-immutable
-you don't have to even count the votes

I think involving some kind of a practical example in the start would open up why smart contracts are so much needed. There's a ridiculous amount of trust we invest in our governments at the moment, and most don't even notice it, because we're so grown into it. The only problem I see in smart-voting is that it should be anonymous and at the same time untraceable, so that voters can't sell their votes.

**Comment by Benudek** [comment]
This should be called e.g. 'Eliminating the need for trust in 3rd parties' Parties should be qualified as organizations or humans in the text

The idea of smart contract is to generate trust only not via relying on organizations, if smart contract s would eliminate trust itself they would defeat their purpose.

**Comment by danieljwonder** [comment]
This is a solid use case and I would suggest linking in with #129
