### ISSUE TITLE
As a Pythonista and a Solidity developer I'm curious about Vyper

### ISSUE THREAD

**Issue by fjrojasgarcia** [ethereumbook/ethereumbook#115]
I have the impression that we are facing a careful work of the Ethereum community. We could highlight 37 commits till today from _Vitalik Buterin_.

**Vyper** is an experimental programming language that aims, among others, the following goals;
**Security, Language and compiler simplicity and Auditability**.

**About the Auditability aims**: **_Vyper code should be maximally human-readable_**. Furthermore, it should be maximally difficult to write misleading code. Simplicity for the reader is more important than simplicity for the writer, and simplicity for readers with low prior experience with Vyper (and low prior experience with programming in general) is particularly important.

In my opinion, it could become the preference of **pythonistas**.

Links;
**Github**: https://github.com/ethereum/vyper
**Read the docs**: http://vyper.readthedocs.io/en/latest/?badge=latest

**Comment by fjrojasgarcia** [comment]
**Iuri Matias** says that _embark-framework_ will support Viper.

**Gitter snippet**

```
one_gitter_user @one_gitter_user  ##:##
Sorry, before open an issue in github, are any plans to include Viper language support in Embark? 
Thanks in advance.

Iuri Matias @iurimatias 02:31
@one_gitter_user yes
```

**Comment by fubuloubu** [comment]
@fjrojasgarcia Thanks for the shoutout! We actually changed the name to Vyper, so that is the current name. Check out this issue for more details: https://github.com/ethereum/vyper/issues/501

**Comment by fjrojasgarcia** [comment]
@fubuloubu noted, Thanks!

**Comment by aantonop** [comment]
Vyper has been added to the section listing High Level Languages. We'll need to do some of the example contracts in Vyper too, to help compare against Solidity.

**Comment by fubuloubu** [comment]
I can volunteer to write some. Most contracts that don't use inheritance can be converted

**Comment by aantonop** [comment]
Very nice progress on this. It will be included in the first edition
