### ISSUE TITLE
How to review transifex format?

### ISSUE THREAD

**Issue by ghost** [ethereumbook/ethereumbook#1159]
Hello, I've translated the first chapter of Ethereumbook in Dutch. Now I would like to verify if everything is done correctly format wise. It seems to be like a JavaScript but how to show the correct format? I've tried several things, did some online searches and asked some developers for help but that hasn't lead to any success as of yet. Can somebody here help me with that?
This is the link -> https://www.transifex.com/aantonop/ethereumbook/language/nl/ and how do I proceed from there? Thank you.
Once I can verify I can make the necessary changes and continue the translation for the other chapters.

**Comment by aantonop** [comment]
The markup is asciidoc. You can use asciidoctor-pdf or asciidoctor-epub3 to
produce formatted books for review.

A docker based set of scripts and configurations for running asciidoctor
can be found at my publishers repo here:

https://github.com/merklebloom/bookbuilder
