### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by 0x0OZ** [ethereumbook/ethereumbook#1161]
on page [smart contracts-vyper](https://github.com/ethereumbook/ethereumbook/blob/develop/08smart-contracts-vyper.asciidoc) 

> Vyper also takes the view that multiple inheritance can make code too complicated to understand—a view tacitly admitted by the Solidity [documentation](http://bit.ly/2Q6Azvo), which gives an example of how multiple inheritance can be problematic.
the referenced link is broken 404: http://bit.ly/2Q6Azvo

**Comment by adityakode** [comment]
I have created a PR, the issue will be fixed as soon as the PR is merged

**Comment by aantonop** [comment]
We will not be "fixing" these links, because they are designed to produce
valid links in the print edition and not in Github. When the book is
rendered as a single file they work fine. They do not work in Github.

**Comment by 0x0OZ** [comment]
Okay @aantonop, but if you think it is a reference in the book itself, it is not, it refers to the old docs of solidity before it was moved.
the old docs for the broken link: https://github.com/ethereum/solidity/blob/release/docs/contracts.rst
A reference to the new docs: https://docs.soliditylang.org/en/latest/contracts.html#multiple-inheritance-and-linearization

**Comment by adityakode** [comment]
@0x0OZ  thanks! I have made the changes and made a PR #1166
