### ISSUE TITLE
Average salary on blockchain.

### ISSUE THREAD

**Issue by chainhead** [ethereumbook/ethereumbook#128]
Hello,
I wrote an article sometime ago, on how to calculate average salary of a group without immediately divulging the individual salaries. Perhaps, it can serve as a simple example to guide folks into decentralized application development. Especially because, it runs into a problem where zSNARKs may have to get involved.

If you are interested in using this example in the book, I will be enthused to improve the implementation.

[LinkedIn post](https://www.linkedin.com/pulse/what-average-salary-your-team-ask-blockchain-nagesh-subrahmanyam/)
[Implementation](https://github.com/chainhead/lister)

Keen to hear back!

**Comment by fjrojasgarcia** [comment]
I'm personaly interested in good examples of zSNARKs, so I support this proposal.

**Comment by aantonop** [comment]
Link to #85
