### ISSUE TITLE
Chapter on Ethereum  usecases

### ISSUE THREAD

**Issue by Benudek** [ethereumbook/ethereumbook#129]
I believe the book would greatly benefit from a chapter of usecases that Ethereum only or at least can implement much better than other application platforms or bitcoin. We have great cloud application platforms and we have bitcoin, what does Ethereum as a programmable money platform add?

‘Usecase?’ for all non bitcoin blockchain technologies is a question with not so straightforward answers. Just saying it’s somehow decentralized isn’t enough. It would need to be clarified what that means for users and developers. Why is that better than what we already have ? Can we implement just some stuff as on aws, but here we have a community behind it instead og a cooperation?

If you check other projects like hyperledger the list of usecases is often supply chain but overall it is not clear why distributed databases couldn’t help, at times blockchains look like a solution in search of a problem.

For bitcoin the usecases are crystal clear, even in the white paper. For Ethereum as great as the idea seems, at least to me the usecases are not clear. Anything I see could be implemented in other platforms, the only exception (a big one though!) are ICOs, which should be a major section in such a chapter for usecases. This might very well be due to my ignorance around Ethereum but I am probably representative for many future readers then :-)

I am not saying these Ethereum specific usecases are not there even though I have difficulties to really Point them out - which is why I would love to see this list in a book:-)

Great technology itself is not enough, it’s about unique usecases or the capacity to implement existing applications in different advantageous ways.

**Comment by fjrojasgarcia** [comment]
In my humble opinion, trying to make understand through this book the true paradigm of decentralization and its particular application in Ethereum, is a task that goes beyond the technical, touching in so many cases sociological and philosophical aspects.

I understand the practical interest of the proposal, but I think that the phenomenon of "Decentralization" is something that the individual has to internalize by her/himself, in the same way that the individual finds her/his space in other phenomena such as "Internet".

In any case, I would like to be wrong and that your proposal had a place in the book.

**Comment by Benudek** [comment]
Appreciate this POV and I am also a fan of decentralization 

But think about bitcoin: you pay with out banks, you do not need a central bank.
AI: you detect cancer melanons with Deep Neural Networks better than humans 

That is straightforward and very valuable.

Do we have such a killer usecase in Ethereum ? Maybe ICOs? Decentralizing as such is great, also proof of stake is innovative. But if it is just that, then Ethereum is just that: a great tool for innovation and Decentralization. But not much more beyond that, there is no real use case that I couldn’t also implement non google cloud or bitcoin. Only (and that also matters) the power relations on the platform are different, hopefully better. You could argue btw, techies eg those defining smart contracts or languages like solidity have a little too much power.

At the end of the day technology exists for real life usage of every day people and I would enjoy reading what Ethereum has to offer here. You cannot really describe a technology without describing the usecases, technology as great as it might be is just an enabler

**Comment by GuillaumeCz** [comment]
Hi there ;) 
I think it might be really interesting to write about the eventual use cases. Even in Vitalik's Ethereum White Paper there is a section about the applications and in my opinion giving ideas about what's possible to make (especially with smart contracts) can make worth it. 
Also, there is so much innovating and interesting projects based on Ethereum (such as ones listed in [State of the Dapps](https://www.stateofthedapps.com/) and others on Github ). 
Ethereum looks like a perfect framework to build many applications : get rid of centralized big companies and "take the power back" ;)

**Comment by Meshugah** [comment]
I think it would be a worthwhile addition to one of the chapters at the very least. Mastering Bitcoin had the transactions in varying scenarios (like the coffee shop). I understand that there it was meant to merely touch base on most of the core concepts and on something as open-ended as with Ethereum this might both be too broad and detract from other possible use cases.

**Comment by diegogurpegui** [comment]
I also think that adding some use cases can help the intented audience of this book (developers & technologists?) understand better how to use this technology.
I also agree that a debate or analysis on decentralization or the benefits of that has no place in this book. However, having a (small perhaps) chapter with some use cases showing different scenarios where smart contracts are user, surely will help the understanding of all the concepts outlined here. We can even include use cases that are already there, no need to predict the future with questionable examples.
At the very end, the goal is to have the read understand the technology, how it works and how to use it. Right?

**Comment by Benudek** [comment]
I guess the author needs to decide eventually if the focus is more tech or also usecases. Can just say, the blockchain specific usecases are quite a discussion in the community. So, if this book could help pointing what ethereum can do here, it would make me happy ;-)

**Comment by ltfschoen** [comment]
Should we include asset-backed stablecoins since they may be instrumental in helping Ethereum  scaling up and for achieving mass adoption of Ethereum use cases by overcoming the volatility of the exchange rate of say ETH, and overcoming high transaction fees so it becomes usable
