### ISSUE TITLE
Ethereum Classic

### ISSUE THREAD

**Issue by splix** [ethereumbook/ethereumbook#138]
@aantonop recently mentioned that it would be good to cover some topics on Ethereum Classic in the book. I have question, to what extent? Do you want to make just simple remark of the project? Or do you want to cover ETC specific topics and software, such as Classic Geth, SputnikVM and Emerald? There're also other changes, such as different monetary policy, difficulty bomb, and so on. There many things actually to cover. I'd like to help with this part if you would be interested

**Comment by aantonop** [comment]
Yes please. I'd like to cover more than a mention. Especially, as you suggested

- Divergence of conensus rules, like difficulty etc
- Specific tools and software, block explorers etc

Any help is much appreciated - from outlines and URLs to complete sections!

**Comment by wbnns** [comment]
@splix Hello, would you like to contribute some of the content that Andreas mentioned?

**Comment by splix** [comment]
@wbnns yes, I'd like to contribute. I'll try to figure what I can add and will send pull requests

**Comment by danieljwonder** [comment]
I wrote up a post on the origins of Ethereum classic and how the fork came to be last year that could probably be restructured to provide some context in this book. I'm just wondering where this would fit within the flow of the book to know how to introduce and present it. I can only see a few small mentions at the moment. 
https://www.danielmcclure.com/ethereum-vs-ethereum-classic/

**Comment by aantonop** [comment]
You can create/add it in a new section "contrib/etc-history.asciidoc". We
will figure out how to merge it. @pyskell

**Comment by danieljwonder** [comment]
@aantonop I actually started writing up a fresh narrative that would fit after the what is Ethereum section, submitted an pull and only noticed that @pyskell was already working on it after so have set up a pull request of our combined work here: https://github.com/pyskell/ethereumbook/issues/1
Can also spin into separate doc if required.

**Comment by pyskell** [comment]
So far this has been partly addressed in: #310 #363 #461 #479 #481 

Suggestions for more contributions:

- [ ] Deep dive into SputnikVM/technicals
- [ ] Emerald Project and associated tools/libraries
- [ ] Mantis client creation (first Scala-based Ethereum client)
- [ ] Cover ETC's various naming systems (there's a chapter on ENS)

**Comment by gitr0n1n** [comment]
Hey guys, just a follow up on this topic. Please contribute to the open source version adjusted for Ethereum Classic post-merge. ETC is now the larges PoW EVM and likely deserves its own technical book given this positioning. @aantonop it would be great to note the PoS capture happening on Ethereum Foundation (ETH) and how PoW help to reduce this risk. Anyway, I hope to see your contributions on this version of the book. Thank you for open sourcing the original content @aantonop and previous contributors. You are all appreciated.

https://github.com/classicbook
