### ISSUE TITLE
MyEtherWallet and MyCrypto

### ISSUE THREAD

**Issue by pjsub** [ethereumbook/ethereumbook#146]
As you may know, one the MEW co-founder forked this latter in order to make MyCrypto (https://mycrypto.com). I think the "Choosing an Ethereum wallet" part in the Introduction section should have, at least, a mention of this fork and explain briefly why this book keep MEW as a reference.

**Comment by aantonop** [comment]
yes, I will need to list both. Awkward!

I plan to use MyCrypto for examples, as I think it has the more sustainable focus and development team/roadmap.

**Comment by diegogurpegui** [comment]
I agree that both should be listed if they are worth it (like any other tool).
Perhaps a one-line explainer of the fork can be enough. By the time the books is finished an extended explanation probably won't be that relevant, right?

**Comment by aantonop** [comment]
Resolved in Client.asciidoc, lightweight clients section
