### ISSUE TITLE
Update recommended specs to run a full node

### ISSUE THREAD

**Issue by nicarq** [ethereumbook/ethereumbook#154]
```
If you want to sync in a reasonable amount of time and store all the development tools, libraries, clients and blockchains we discuss in this book, you will need a faster and better equipped computer:

Recommended:

* Fast CPU with 4+ cores
* 16GB+ RAM
* Fast SSD with at least 250GB free space
* 25+ MBit/sec download Internet service
```

Currently the size of the Ethereum blockchain is over 337GB (https://bitinfocharts.com/ethereum/). So I would suggest increasing the 250GB of free space to 500GB.

**Comment by aantonop** [comment]
@Nykho would you like to try a Pull Request to add the current requirements and a link to check in the future?

**Comment by nicarq** [comment]
@aantonop sure!! will do today
