### ISSUE TITLE
add Appendix about laws around world about Smart Contracts.

### ISSUE THREAD

**Issue by EvertonMelo** [ethereumbook/ethereumbook#192]
Hi Andreas, 

I hear a lot of criticism about Criminalization of "Smart Contracts" but I have never seen anyone commenting on laws throughout the world, even though they are not the focus of their work, I would add in my opinion.

Kind regards.

obrigado.

**Comment by EvertonMelo** [comment]
sample:

Brazil Laws abou ICO/Smart Contracts:
http://www.cvm.gov.br/subportal_ingles/menu/international/ico_statement.html ( in englesh ) 
or the original in Portuguese.
http://www.cvm.gov.br/noticias/arquivos/2017/20171011-1.html

**Comment by ltfschoen** [comment]
Recent economic report to congress in the USA page 201-226 https://www.congress.gov/115/crpt/hrpt596/CRPT-115hrpt596.pdf

**Comment by EvertonMelo** [comment]
@aantonop 

Hi, 

What would be the best option for Organized this Appendice  ?

= Countries 

or 

= Continents 

or Together

exemplo: 

= North America
== USA; THE 2018 JOINT ECONOMIC REPORT, cap 9 - ( pages 201-226 ) 

= South America
== Brazil, Considering the growth of the so-called Initial Coin Offerings

**Comment by EvertonMelo** [comment]
@ltfschoen 

thank you for your contribution.

Do you know how to tell me, if the regulamentation the New york State about Blockchain if she talks about ICO or Smart Contracts

**Comment by aantonop** [comment]
This topic is outside the scope of a technical book like Mastering Ethereum

**Comment by EvertonMelo** [comment]
@aantonop 

ok.
