### ISSUE TITLE
Add ERC875 example to book

### ISSUE THREAD

**Issue by SmartLayer** [ethereumbook/ethereumbook#193]
Hey Andreas, hope all is well since we met in Sydney, was great to see your talk! 

ERC875 is a non fungible standard that includes an optional atomic swap function, even though it is in draft phase, it should be included in the book. 

I believe this because it shows some of the future possibilities for atomic swaps and efficient non fungible transfers and has an implementation example in java which will be of interest to some readers (signature verification, expiry timestamp and release of funds in one transaction)

Let me know your thoughts and if you'd like to go through with it, I can make a draft. 

https://github.com/ethereum/EIPs/issues/875

Example implementation: https://github.com/alpha-wallet/ERC875-Example

Thank you,
Weiwu

**Comment by aantonop** [comment]
@colourful-land Maybe start an outline in the "contrib" folder?

**Comment by JamesANZ** [comment]
@aantonop could this be of assistance or were you thinking of something else? https://medium.com/bitfwd/erc875-a-new-standard-for-non-fungible-tokens-and-cheap-atomic-swaps-93ab85b9e7f9
