### ISSUE TITLE
Suggestion to add a note that gas prices might be different as well as 1 or 2 sentences about the effect of increasing/decreasing

### ISSUE THREAD

**Issue by boue** [ethereumbook/ethereumbook#255]
In the section entitled "Sending ether from MetaMask" of the Introduction chapter user could be subject to a different gas price (2 in my case). A short clarification that gas prices might fluctuate, that it determines how fast your transaction will be mined, and therefore can be increased or decreased would help. As I see on the table of contents there is a whole chapter dedicated to GAS but want to steer users away from thinking perhaps something is wrong with their setup since they are in the initial portion of the book.

**Comment by aantonop** [comment]
Excellent suggestion. An easy PR for some contributor. Anyone want to tackle it?

**Comment by boue** [comment]
@aantonop I've just created one, it is up for review: https://github.com/ethereumbook/ethereumbook/pull/270
