### ISSUE TITLE
Ensure all headings have asciidoc reference anchors and all references point somewhere

### ISSUE THREAD

**Issue by aantonop** [ethereumbook/ethereumbook#279]
I could use some extra help with this issue. 

In asciidoc, every chapter heading, section heading, figure, table, and code example, can be referenced from anywhere in the book. To do that, each of the above must have an _anchor_, which is a unique name inside double square brackets like [[anchor]]. See this example below:

```
[[transaction_chapter]]
== Transactions

[[transaction_example]]
.An example of a transaction in hex
----
453425235325345
----

[[metamask_transaction_example]]
.A screenshot of MetaMask doing a transaction
image::images/metamask_screenshot.png[A screenshot of Metamask]
```

It doesn't matter what the variable name inside the [[]] is, as long as it is unique. I prefer to use descriptive names with underscore between words, up to 2-4 words in length. 

Elsewhere in the document you can refer back (or forwards) to a section, example, table or figure, by including the reference name inside angle brackets, like this:

```
As we saw in example <<transaction_example>>, a transaction is created 
and then Metamask shows you an approval screen (see <<metamask_transaction_example>>). 

```

When rendered by O'Reilly for print these are replaced by the heading, title, or caption. When rendered in an ebook or HTML they also become hyperlinks to the section. 

Help me make it all work by doing the following:

* A pull request adding anchors to every section, heading, image, code example.
* If there are references that don't point anywhere like <<this_doesnt_exist_yet>>, then go and add a [[this_doesnt_exist_yet]] somewhere else in the text where it makes sense and points to something useful, like a section heading in another chapter.
* Create an issue if you find a reference that doesn't have a good place to point to and is left "dangling"

**Comment by abhiShandy** [comment]
is there a need to anchor TIPS and WARNINGS?

**Comment by aantonop** [comment]
No

**Comment by nuke-web3** [comment]
@aantonop - close #279 ? and/or add this to contributions page for future reference?
