### ISSUE TITLE
https://ethereumbook.info/can't be reached

### ISSUE THREAD

**Issue by sgerhardt** [ethereumbook/ethereumbook#3]
It's referenced in [preface.asciidoc](https://github.com/ethereumbook/ethereumbook/blob/develop/preface.asciidoc#how-to-contact-us)

**Comment by aantonop** [comment]
The website has not been developed yet. It will be a landing page with information about the book. I expect to have it built in the next 2 months.

**Comment by ghost** [comment]
I'd make a note of that next to the link or remove the link until it's live then.
