### ISSUE TITLE
Sending value in a contract creation

### ISSUE THREAD

**Issue by nicksavers** [ethereumbook/ethereumbook#313]
It's possible to send a value in contract creation ('_[contract registration](https://github.com/ethereumbook/ethereumbook/blame/324b691e80449f64f63a4a37c3145cf6daafa3f5/transactions.asciidoc#L314
)_'). That value would then be immediately added to the balance of the newly created contract. 

AFAIK, that is disabled by default in Solidity, so in order to receive ether, the fallback function must be marked payable. And make sure you have a way to retrieve the ether, otherwise (with the consensus rules as they are) it will just stay in there forever. http://solidity.readthedocs.io/en/v0.4.21/contracts.html?highlight=creation#fallback-function

See also page 9, paragraph 7 item (78) in the Yellowpaper https://ethereum.github.io/yellowpaper/paper.pdf

![New account with value](https://i.imgur.com/Jz1DDqd.gif)

**Comment by fjrojasgarcia** [comment]
Pointing to your Gitter note --> you can pre-fund an account .... and only retrieve it after contract creation. Nobody would know that there is no private key to the address, just a transaction to create a contract to send the ether value somewhere.

**Comment by fjrojasgarcia** [comment]
More of your awesome clarifications from Gitter --> 
... «Since a contract address is derived from the sender address and nonce, you can know the contract address ahead of time and send ether to it. Then only when you actually send the contract creation transaction, it can be spent. Not before.
To the outside world, until then it would just look like a normal EOA.»

**Comment by fjrojasgarcia** [comment]
The address for an Ethereum contract is deterministically computed from the address of its creator (sender) and how many transactions the creator has sent (nonce). The sender and nonce are RLP encoded and then hashed with Keccak-256.

https://ethereum.stackexchange.com/questions/760/how-is-the-address-of-an-ethereum-contract-computed

**Comment by starmanzz9** [comment]
```
contract DAPP {
    
    function DAPP() payable {
        //accept Ether during deployment
        //..
    }
    
    event Donation(address _addr, uint _val);
    function () public payable { //fallback
        // accept Ether after deployment
        assert(msg.value > 0);
        emit Donation(msg.sender, msg.value);
    } 
}
```
For counterfactual contract deployment (i.e. computing contract addresses before deployment), EOA nonce starts at 0 but the Contract nonce starts from 1. `address(keccak256(rlp_encode([addr, nonce])))`. This allows EOA/contract to send funds to counterfactual contract addresses that'll be depolyed later by base contract/EOA.

Things might break after metropolis, https://github.com/ethereum/EIPs/issues/86 aka https://github.com/ethereum/EIPs/issues/208 and at ETH Core Dev meeting 37 where VB suggested  a new `create2()` function for future counterfactual contracts / state channels. There's no EIP yet for this part. https://youtu.be/vKumx5CIA-k?t=1h35m42s

Ref : 
http://martin.swende.se/blog/Ethereum_quirks_and_vulns.html 
https://blog.aragon.one/advanced-solidity-code-deployment-techniques-dc032665f434 
https://medium.com/spankchain/a-state-channels-adventure-with-counterfactual-rick-part-1-ce68e16252ea
