### ISSUE TITLE
Create an appendix of EVM opcodes and gas cost

### ISSUE THREAD

**Issue by aantonop** [ethereumbook/ethereumbook#317]
Use this source: https://github.com/trailofbits/evm-opcodes
(with attribution)

Convert GitHub Markup to Asciidoc Markup and export as appendix section in its own asciidoc file.

**Comment by fjrojasgarcia** [comment]
I'm creating an auto generator for the OPCODES and Gas appendix based on the source indicated.

**Comment by fjrojasgarcia** [comment]
Related to https://github.com/ethereumbook/ethereumbook/pull/325 - Auto generation of the appendix for OPCODES and its Gas consumption.
