### ISSUE TITLE
Upgradeability of smart contracts

### ISSUE THREAD

**Issue by aantonop** [ethereumbook/ethereumbook#318]
Add some sections and discuss the upgradeability of smart contracts and some of the patterns created by OpenZeppelin and others to achieve these goals. 

Useful reading:
https://medium.com/@mikecalvanese/flexible-upgradability-for-smart-contracts-9778d80d1638

**Comment by SylTi** [comment]
I'm working on a first draft for this

**Comment by fiiiu** [comment]
@SylTi I just opened #486 with a (very short) intro to OpenZeppelin and zeppelin_os, apologies for stepping over, please check if it is of use. 

BTW we are working on an interesting upgradeability pattern for zeppelin_os that might be worth including, let me know if you want to sync on this!

**Comment by SylTi** [comment]
@fiiiu don't worry, no problems at all, happy to see more contributors 👍 
And I was working on the more technical part anyway :)
