### ISSUE TITLE
Yellowpaper comprehension guide

### ISSUE THREAD

**Issue by fjrojasgarcia** [ethereumbook/ethereumbook#329]
In my opinion, it would be interesting to provide the readers of the book with access and understanding of such an important document as the [Yellowpaper](https://ethereum.github.io/yellowpaper/paper.pdf).

We could highlight aspects such as, why it exists, which is fundamentally its content, fundamental concepts, conventions used, basic maths needed for its understanding, and appendices.

Any help will be welcome.

**Comment by aantonop** [comment]
The author  (@chronaeon) of the "beigepaper" (chronaeon/beigepaper) has also contributed some PRs. The beigepaper is a slightly more "accessible" rewrite of the yellow paper.

**Comment by aantonop** [comment]
Gav Wood suggested we work to include the Yellow Paper as an appendix. We will need to figure out how to convert it to asciidoc

**Comment by fjrojasgarcia** [comment]
I've seen it! :-)
Taking a look at @chronaeon's work, it looks like very much in line with what I was proposing.
If he agrees to offer his content to the book it will be a great contribution.

I have the doubt of how it will be included in the book.
I'd leave open this issue till its materialization.

For concrete reference, we can jump here to the [Rewrite of the Yellowpaper in non-Yellowpaper syntax](https://github.com/chronaeon/beigepaper)

**Comment by chronaeon** [comment]
Definitely would be happy to offer my content. I hope to take a more thorough look at @ethereumbook this week.

On another note, [this](https://github.com/benjaminion/YellowPaper_CheatSheet/blob/master/YPCheatSheet.pdf) is a truly fantastic Yellowpaper  reference from Ben Edgington (@benjaminion) of the protocol engineering team at ConsenSys. Since we're on the topic of adding appendices, it's worth noting that this would make a great appendix for the original Yellowpaper, although I haven't submitted a pull request for that yet.

**Comment by fjrojasgarcia** [comment]
At this point it seems that to be able to integrate **"The Beigepaper"** into the book, an elaborate work is necessary to adapt its original format (LaTex) to asciidoc.

At the moment I proceed with the preliminary steps of branch creation and automatic conversion.

1. [beigepaper fork created](https://github.com/ethereumbook/beigepaper)
2. [Working branch created](https://github.com/ethereumbook/beigepaper/tree/transformation-to-asciidoc)
3. Automatic latex to asciidoc conversion (pandoc) - lot of work pending

`pandoc -s beigepaper.tex -t asciidoc -o beigepaper.asciidoc`

I await the approval and supervision of these steps by @chronaeon.

**Comment by fjrojasgarcia** [comment]
Adding reference "Yellowpaper Cheat Sheet" #532 provide by @chronaeon

**Comment by onggunhao** [comment]
Is this still an open issue? Can help out if needed
