### ISSUE TITLE
Seeking consensus for Line Feeds represented as in *Nix text files.

### ISSUE THREAD

**Issue by fjrojasgarcia** [ethereumbook/ethereumbook#365]
I would like to emphasize the importance of all contributors using a unified system to indicate the **end of line** in the documents of this repository.

I understand that there should be no consensus problem to use the LF (\n) character as the standard in *Nix systems.

Any feed back on this point would be appreciated.

**Comment by aantonop** [comment]
All submission should use Unix-like line endings: LF (not CR, not CR/LF). All the postprocessing is done on Unix-like systems. Incorrect line endings, or changes to line endings cause confusion for the diff tools and make the whole file look like it has changed. 

If you are unsure or your OS makes things difficult, consider using a developer's text editor such as Atom.
