### ISSUE TITLE
Make Double-Spend Prevention Obvious

### ISSUE THREAD

**Issue by thoragio** [ethereumbook/ethereumbook#388]
I'm am reading the draft in this repo to educate myself about Ethereum. One point that was not clear to me was how Ethereum prevents double-spending. I was looking for the equivalent of Bitcoin's UTXOs, and eventually found out that one of the functions of the transaction nonce was to prevent double-spending, as highlighted in this post:

https://ethereum.stackexchange.com/questions/27432/what-is-nonce-in-ethereum-how-does-it-prevent-double-spending/27435#27435

I think it would be helpful to make this point more obvious toward the beginning of the "Transactions" chapter by explicitly stating that the transaction nonce is what protects against double-spending in Ethereum.

**Comment by chanan-sack** [comment]
done, was added in recent pr as an additional paragraph to "The transaction nonce"
