### ISSUE TITLE
DRAFT status of the document following the recommended practices

### ISSUE THREAD

**Issue by fjrojasgarcia** [ethereumbook/ethereumbook#396]
This issue point to #381

I'd suggest at least indicating DRAFT status as following;

```
= Title of the document: This is the subtitle
:revnumber: v1.1
:revdate: 15.05.2017
:revremark: First draft
```
I'd suggest to adopt this practice or another more optimal, among the participants of the repository. I would do so, at least while there are parts of the document pending development.

**Comment by aantonop** [comment]
Some of this will probably be queued up for a second edition. We are about 1 month from the draft-to-editor, two months from final-to-production.
