### ISSUE TITLE
Capitalize bitcoin "correctly": Easy task for new contributors

### ISSUE THREAD

**Issue by aantonop** [ethereumbook/ethereumbook#413]
In my first book Mastering Bitcoin, I stubbornly refused to capitalize bitcoin. The network, currency, blockchain: all "bitcoin". 

I'm now faced with cognitive dissonance and a stylistic mess, because I continued that practice in this book. I used "bitcoin" everywhere. Unfortunately, with Ethereum and ether, the difference is obvious and Ethereum is a proper noun. That makes sentences like "Unlike Ethereum, bitcoin is...." where one term is capitalized and the other isn't. 

Anyone care to help? I need a focused PR that fixes this across all the asciidoc files. 
* Find "[Bb]itcoin"
* Replace with "Bitcoin" when referring to the system, blockchain, network.
* Replace with "bitcoin" when and only when referring to the currency and currency unit.

**Comment by chanan-sack** [comment]
on it, theres not too many mentions so its a piece of cake.

**Comment by chanan-sack** [comment]
done, should be closed

**Comment by NukeManDan** [comment]
@aantonop - close #413 ?
