### ISSUE TITLE
Design architecture diagram for Auction DApp

### ISSUE THREAD

**Issue by aantonop** [ethereumbook/ethereumbook#440]
We need an architecture diagram for the Auction DApp #419, showing the various components and how they connect, including:

- The Auction contract
- The ERC721 NFT contract
- Swarm
- Whisper
- Web3.js
- React/Vue front end
- ENS

@iNDicat0r If you could make a very rough draft, perhaps just a photo of pencil/paper drawing of boxes, we have a few designers in the team who could make it look great, add logos and icons etc. All we need is the *correct* layout of what talks to what, then the designers can make it pretty

**Comment by iNDicat0r** [comment]
@aantonop Working on it

**Comment by iNDicat0r** [comment]
![architecture](https://user-images.githubusercontent.com/13126311/38516626-568afda6-3c40-11e8-9b89-bdd015b27f42.png)

Quick overview:
1. Auction house contract holds auction info including bids, owner, swarm refs
2. DeedRepository tracks ownership of tokens registered with the contract.
3. Swarm is used to store metadata such as images
4. Whisper is used for messaging by allowing accounts to subscribe to topics(auction ids)
5. Web3 is injected to the browser by metamask and used to interact with the backend components
6. UI/Components are built using Vue2.x, which utilizes the injected web3 instance.

**Comment by aantonop** [comment]
Great, that's perfect. I can submit that to O'Reilly designer to stylize.
