### ISSUE TITLE
Easy editing work: Heading style normalization and standardization 

### ISSUE THREAD

**Issue by aantonop** [ethereumbook/ethereumbook#446]
We need to normalize heading styles across the book:

Please do one pull request PER asciidoc file, to avoid large merges. Adjust heading style in each section as follows:

* Top level heading is level 2 (level 1 is the book title itself). Each asciidoc file should start with a "==" heading.
* All lower case, except for first letter, proper nouns and acronyms. "What is this thing?", "What is the Ethereum sprocket?" "Who created the Ethereum Name Service (ENS)"
* Acronyms are spelled out, capitalized, with the acronym in parentheses. 
* No period at the end. Question mark if it is a question (generally avoid question headings, unless really appropriate)
* Should include a unique anchor (see #279), all lower case, underscore separated. 
* Headings should be followed by a blank line.
* Heading should be followed by a paragraph of text, not a lower-level heading without any text. If you find one like this, add a TODO comment (line of 4 slashes "////", line with "TODO: add paragraph", line of 4 slashes)

**Comment by fjrojasgarcia** [comment]
Should we consider them [contribute's ](https://github.com/ethereumbook/ethereumbook/blob/develop/CONTRIBUTE.md) notes?

**Comment by NukeManDan** [comment]
At this point, think this is closed @aantonop ? close #446 ?
