### ISSUE TITLE
Which EIP reverted the 20 million DoS transactions on Ethereum blocks 2.2-2.7 million?

### ISSUE THREAD

**Issue by pyskell** [ethereumbook/ethereumbook#477]
https://github.com/ethereumbook/ethereumbook/blob/c9095de862226b3c556fafd669d3dd6cea57cd17/clients.asciidoc#L459

There's a reference to a change in the network to remove 20 million spam transactions. However I'm having trouble locating the EIP that did this and am wondering if there was no network change and it was simply a change to how clients handle these transactions (rather than truly removing/changing any data).

I'm aware of EIP-150 that made the attack far more expensive (thus stopping it) but which EIP, if any, actually removed this data from the chain. EIP-161 seems to accomplish something like this but only does so after a specific block number (no retroactive changes).

EIP-150: http://eips.ethereum.org/EIPS/eip-150
EIP-161: http://eips.ethereum.org/EIPS/eip-161

**Comment by pyskell** [comment]
Further, I think this paragraph is referring to https://github.com/ethereum/EIPs/issues/168 which remains open/not accepted.

**Comment by lrettig** [comment]
[EIP-161](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-161.md) did this. In short, it was not an irregular state transition like the Dao fork but the result was similar. In this case, EIP-161 made a change to the protocol regarding how to handle the case where an account is or becomes "empty" after a transaction (zero nonce, no balance, no code). After the change, such accounts are actually deleted from the state after they are "touched" (see EIP for definition). So technically speaking EIP-161 and the associated hard fork ([Spurious Dragon](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-607.md)) didn't alter the state directly, but rather made it possible to alter the state _according to a new set of rules_ after the fork. A bunch of transactions were subsequently fired which cleared these spam accounts from the state.

EIP-150 was a stopgap measure to stop the spam, as you noted. The response to the attack was a series of two hardforks -- one immediate one ([Tangerine Whistle](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-608.md)) followed by Spurious Dragon to revert some of the damage.

[EIP-168](https://github.com/ethereum/EIPs/issues/168) is a related, open EIP that would clear "dust" accounts (i.e., accounts with a negligible ether balance) from the state, but as you noted it hasn't been accepted, implemented, nor merged.

**Comment by pyskell** [comment]
Awesome, thanks for clearing that up for me!
