### ISSUE TITLE
Diagram: EVM context when running a smart contract

### ISSUE THREAD

**Issue by aantonop** [ethereumbook/ethereumbook#496]
When a smart contract is running, it has a very limited context (state) it can access through the EVM.

We need a diagram that shows this: A circle or box in the middle that is the EVM and within it the contract. Surrounding it are boxes representing the various parts of the context: one box for the calling transaction context, one for the contract variables, one for the blockchain etc. Each of these boxes contain a list of items that can be accessed from that context (the sender of the transaction, the startGas) and the name of each item as it exists in Solidity (eg. msg.sender).

**Comment by ltfschoen** [comment]
I'm in the process of creating an initial sketch to get this moving

**Comment by aantonop** [comment]
Super!

**Comment by ltfschoen** [comment]
I've run out of time today but here are some messy sketches to get the ball rolling 

![20180421_162503](https://user-images.githubusercontent.com/6226175/39081312-6b50448a-4582-11e8-93e0-f637e643359b.jpg)

![20180421_162514](https://user-images.githubusercontent.com/6226175/39081313-70cfa73e-4582-11e8-8f4c-23198f9cdc3c.jpg)

![20180421_162550](https://user-images.githubusercontent.com/6226175/39081316-7759e056-4582-11e8-8813-a879961385dd.jpg)

![20180421_162529](https://user-images.githubusercontent.com/6226175/39081314-73ba6d62-4582-11e8-9a2d-59a16307b7fe.jpg)

These are some links that have good diagrams or explanations. This site https://www.draw.io/ is free to draw diagram:
* https://medium.com/@preethikasireddy/how-does-ethereum-work-anyway-22d1df506369
* https://ethereum.stackexchange.com/questions/268/ethereum-block-architecture/6413
* https://hype.codes/hyperledger-announces-sawtooth-ethereum-integration
* https://blog.keep.network/miners-arent-your-friends-cde9b6e0e9ac
* https://aryannava.com/2017/05/
* https://dzone.com/articles/blockchain-ethereum-part-1
* https://www.google.com.au/imgres?imgurl=http%3A%2F%2Fwww.combined-coins.com%2Fimg%2Fcontent%2Fhow1.png&imgrefurl=http%3A%2F%2Fwww.combined-coins.com%2F&docid=opKbjRdq3z_wSM&tbnid=vG2OtUnu8VKLZM%3A&vet=12ahUKEwjthoyX6snaAhXBlJQKHYjGBw04ZBAzKB4wHnoECAAQHw..i&w=984&h=427&bih=521&biw=801&q=evm%20ethereum&ved=2ahUKEwjthoyX6snaAhXBlJQKHYjGBw04ZBAzKB4wHnoECAAQHw&iact=mrc&uact=8
* https://www.google.com.au/imgres?imgurl=https%3A%2F%2Fars.els-cdn.com%2Fcontent%2Fimage%2F1-s2.0-S0167739X17318332-gr6.jpg&imgrefurl=https%3A%2F%2Fwww.sciencedirect.com%2Fscience%2Farticle%2Fpii%2FS0167739X17318332&docid=KioY8eyntYtq9M&tbnid=AHJFdNOgWXPO1M%3A&vet=12ahUKEwjthoyX6snaAhXBlJQKHYjGBw04ZBAzKCMwI3oECAAQJA..i&w=495&h=213&bih=521&biw=801&q=evm%20ethereum&ved=2ahUKEwjthoyX6snaAhXBlJQKHYjGBw04ZBAzKCMwI3oECAAQJA&iact=mrc&uact=8
* https://www.ntt-review.jp/archive/ntttechnical.php?contents=ntr201712ra1_s.html
* http://www.imperial.ac.uk/media/imperial-college/faculty-of-engineering/computing/public/AlanVey.pdf
* https://github.com/comaeio/porosity/wiki/Ethereum-Internals
* http://solidity.readthedocs.io/en/v0.4.21/units-and-global-variables.html
* http://yellowpaper.io/
* https://github.com/ethereum/wiki/wiki/JSON-RPC
* https://www.reddit.com/r/ethereum/comments/3k4h3w/basic_questions_about_the_ethereum_evm_and_state/
* https://github.com/ethereum/wiki/wiki/JSON-RPC

**Comment by ltfschoen** [comment]
Here's an image of the EVM Context that I just finished, and a link to the original on Lucidcharts. Feedback appreciated:

License: CC-BY
Author: @ltfschoen

[https://www.lucidchart.com/invitations/accept/def50297-b59e-4b82-8d78-1a1b8e9ff2e5](https://www.lucidchart.com/invitations/accept/def50297-b59e-4b82-8d78-1a1b8e9ff2e5)

![ethereum evm context](https://user-images.githubusercontent.com/6226175/39097205-ab1e6b4e-469c-11e8-998d-ceea683b048f.png)

**Comment by aantonop** [comment]
Can't use a CC-BY-SA license. See "CONTRIBUTE.md". The book is originally
(first year) licensed CC-BY-NC-ND, which is incompatible with CC-BY-SA. We
will eventually re-license it as CC-BY-SA, but for the first year it is
not.

We need a license of CC-BY to even consider adding contributions.

**Comment by ltfschoen** [comment]
That's cool, I've updated the image to be CC-BY so it may be considered for the book

**Comment by aantonop** [comment]
Fantastic! Will include this image - thanks
