### ISSUE TITLE
Wallet chapter says "content complete" but maybe consider multisig wallets?

### ISSUE THREAD

**Issue by stefek99** [ethereumbook/ethereumbook#522]
https://github.com/ethereumbook/ethereumbook/blob/develop/wallets.asciidoc

Definitely worth adding a mention.

**Comment by danieljwonder** [comment]
If I'm not mistaken most, if not all, multi-sig wallets are actually smart contracts built on the Ethereum blockchain so they are not a unique type of wallet but a contract that uses the base wallets for interaction. That could be explained though?
