### ISSUE TITLE
Inconsistent version reference of solidity compiler

### ISSUE THREAD

**Issue by naveensrinivasan** [ethereumbook/ethereumbook#529]
The `pragma solidity ^` version within the chapters refers to multiple different version. It would be nice to have consistent version across. Thoughts on this?

**Comment by SylTi** [comment]
I would not recommend just changing the version number. Some stuff might just not compile afterward. 
Also the solidity version is the minimum version, it will use the latest version you have installed anyway.

**Comment by naveensrinivasan** [comment]
@SylTi Can you specific as to which things would not compile with the latest version?
