### ISSUE TITLE
Yellowpaper Cheat Sheet

### ISSUE THREAD

**Issue by chronaeon** [ethereumbook/ethereumbook#532]
@fjrojasgarcia @aantonop if you're still considering adding the Yellowpaper as an appendix, consider adding this Yellowpaper cheat sheet along with it from @benjaminion: https://github.com/benjaminion/YellowPaper_CheatSheet/blob/master/YPCheatSheet.pdf

**Comment by fjrojasgarcia** [comment]
Thanks a lot @chronaeon! Superb!
