### ISSUE TITLE
Inter-chain blockchain protocols

### ISSUE THREAD

**Issue by fjrojasgarcia** [ethereumbook/ethereumbook#632]
I find it interesting to propose a chapter dedicated exclusively to Inter-chain blockchain protocols.

Links:
[Polkadot Vision](https://polkadot.network/#whatisit)
[012 - Polkadot Network - TECHNOLOGIES THAT ALLOW US TO TRUST - Dr. Gavin Wood](https://youtu.be/qOuCmwRY5o4)

**Comment by tomas-aftalion** [comment]
Reminds me of a recent article in [MIT Tech Review](https://www.technologyreview.com/s/611187/how-to-get-blockchains-to-talk-to-each-other/). They should have mentioned Polkadot.
