### ISSUE TITLE
Some tips on writing ?

### ISSUE THREAD

**Issue by fankeke** [ethereumbook/ethereumbook#664]
Thanks for the great work you guys did.

if only there are more **_pictures_** to describe the meaning you want to deliver, it would be better.

it is hard for beginners to digest so many words.  easy to use up  enthusiasm. 

Thanks many.

**Comment by aantonop** [comment]
I'm working on diagrams now. I would really appreciate suggestions on which sections could use visualization/diagrams. Are there specific sections that you think I should focus on?

**Comment by sheluchin** [comment]
Just a thought, but perhaps it would be helpful to use something like [Mermaid](https://mermaidjs.github.io/) for creating the diagrams? It plays nicely with revision control unlike just copying image files into folders and replacing them with every edit.

**Comment by aantonop** [comment]
The diagrams are done by a professional illustrator/designer at O'Reilly
Media, to their style.

I just provide a rough draft to guide the designer, which they replace. I'm
probably going to use Grafio for that, but I'll look into Mermaid

**Comment by WizardOfAus** [comment]
@aantonop It would be nice to have some visualizations in chapters where it can get a bit dry. I think for example: https://github.com/ethereumbook/ethereumbook/blob/develop/smart-contracts.asciidoc could do with simple/some images to help the mind focus and visualise

e.g. 

![smart-contracts](https://user-images.githubusercontent.com/9751831/43248525-09ac3e72-90b0-11e8-81ff-e41706c6bf32.png)

(taken from https://blockchainhub.net/smart-contracts/)
