### ISSUE TITLE
Some invalid links - ganache

### ISSUE THREAD

**Issue by WizardOfAus** [ethereumbook/ethereumbook#720]
For example in https://github.com/ethereumbook/ethereumbook/blob/develop/intro.asciidoc

<img width="889" alt="screen shot 2018-07-27 at 2 08 33 am" src="https://user-images.githubusercontent.com/9751831/43296271-57cb5510-9142-11e8-9490-ce1e7ca1ba2c.png">

The links to see 'ganache', 'testnets' etc point nowhere. For ganache, there is no other mention on the page.

**Comment by chanan-sack** [comment]
this was edited (removed the unnecessary) and the issue should be closed.
