### ISSUE TITLE
i can't use "inject web3" in remix IDE

### ISSUE THREAD

**Issue by GoddessLuBoYan** [ethereumbook/ethereumbook#736]
Error:No injected Web3 provider found. Make sure your provider (e.g. MetaMask) is active and running (when recently activated you may have to reload the page).
![default](https://user-images.githubusercontent.com/38455509/43511742-c5361866-95ab-11e8-9627-baf5fac0dfc3.PNG)

However, i have it.
![default](https://user-images.githubusercontent.com/38455509/43511774-e2d408d8-95ab-11e8-9b87-77dd95f86f90.PNG)

So, how can I use "inject web3" and upload my solidity codes to my account?

First issue, thank you very much!
(My English is bad.If you can, please use Chinese, thanks)

**Comment by GoddessLuBoYan** [comment]
It's my full webpage
![rtx](https://user-images.githubusercontent.com/38455509/43512190-fde359c0-95ac-11e8-9a17-7148c7c6fa2e.png)

**Comment by GoddessLuBoYan** [comment]
Well, maybe I must use http://remix.ethereum.org but not IDE on my disk
however, when the webpage starts compiling, it will never complete.......

**Comment by GoddessLuBoYan** [comment]
And I can't set the compiler version

**Comment by GoddessLuBoYan** [comment]
I have done. I should use firefox but not chrome

**Comment by Drjacky** [comment]
@GoddessLuBoYan Have you found the solution for Remix **IDE**?

The issue with Chrome is solved if you're not using HTTP**S**

**Comment by formulaRoot** [comment]
Try this:

https://github.com/smartcontractkit/full-blockchain-solidity-course-py/discussions/1414
