### ISSUE TITLE
Advocating for Mainnet full node

### ISSUE THREAD

**Issue by eyezick** [ethereumbook/ethereumbook#77]
Question: Why recommend new Ethereum devs to run Mainnet nodes?

Advantages: 

- Can interact with other live contracts
- Verify own transactions
- Deploy own contracts

Disadvantages:

- Longer setup time
- Hardware resource cost
- **Costs ETH to deploy/test/interact with contracts**

Arguably, I'd say a combination of a Ropsten local node and Testrpc would be simpler to set up a dev environment. 

Advantages: 

- Blockchain size/sync time: My current Ropsten blockchain is 8.02 GB, and increases by ~.1 GB per day. Fast synced up within a couple hours IIRC.
- No real money cost to deploy/test contracts
- Ropsten is still a 'live' blockchain
- Testrpc is a private chain running on your box, but facilitates automated testing
- Testrpc is already integrated with Truffle, the mainstream framework for development on Ethereum

Disadvantages:

- Can't deploy to Mainnet

For final deployment to Mainnet, there are still easy options like MEW or Metamask available.

**Comment by aantonop** [comment]
Will add something about this to clients.asciidoc. Great suggestion, thanks

**Comment by aantonop** [comment]
Thank you @eyezick 

New section added. Please review and tell me what you think
df658d94bab8d8cd4eaffcb14cd57a17e929005a
