### ISSUE TITLE
Simple non-currency tutorial

### ISSUE THREAD

**Issue by danielquinn** [ethereumbook/ethereumbook#78]
As someone new to Ethereum, I've been spending a lot of time searching for a tutorial that will allow me to store small amounts of arbitrary data in the blockchain, but every tutorial out there seems to think I want to keep track of money or apply logic to what's getting stored.

Often I find that the most effective tutorials are the ones that focus on one feature at a time, so I would suggest that you have one tutorial that does the simplest of things: put data in the blockchain, and then build on that step from there, allowing for increments and triggering other contracts etc.

**Comment by stefek99** [comment]
Storing data on the blockchain is expensive. IPFS is more fit for purpose.

If you want to store a number, look at the default code when you visit: https://ethfiddle.com/

```
pragma solidity ^0.4.18;
contract SimpleStore {
  function set(uint _value) public {
    value = _value;
  }

  function get() public constant returns (uint) {
    return value;
  }

  uint value;
}
```

**Comment by danielquinn** [comment]
Not to be rude, but an appropriate answer to *"how do I store an arbitrary number on the blockchain"* is not *"it's expensive, use IPFS"*.  The project I have in mind already has IPFS in mind, but I want to store small amounts of information in the blockchain too.

I appreciate the offering of sample code, but as a newbie, *this means nothing to me*.  I created this issue to point out that there was no simple tutorial outlining how to do the simplest of things.  An explanation of what the code above does, how to execute it and see the results -- that's what's needed if you're hoping to get new developers on board.

**Comment by stefek99** [comment]
Sorry.

I'm not offering code sample.

What I'm offering...

The website - https://ethfiddle.com/

>  look at the default code when you visit

**DEFAULT CODE**

How often does one see an email with predefined body? Of course Google does it, but they are the most powerful entity on the planet... 

All this exercise is too explain that storing data... 

*(not feeding the troll, not engaging in pointless discussion on the internet)*

**Comment by stefek99** [comment]
For sake of the argument - my intention was not to present a code sample but to emphasise:

> default code when you visit: https://ethfiddle.com/

Storing data on the blockchain apparently is so fundamental, it is `predefined hardcoded default` value when you visit the website.

**Comment by aantonop** [comment]
Added data storage to the outline for dapps chapter. We will consider various options, including the balance between on-chain and off-chain data storage
