### ISSUE TITLE
Not mentioned as contributor in book?

### ISSUE THREAD

**Issue by Arvanaghi** [ethereumbook/ethereumbook#819]
Hi, I wrote a big chunk of the EVM/disassembly chapter per @aantonop's request. I don't see my name acknowledged in the preface of the book with the other contributors.

https://github.com/ethereumbook/ethereumbook/graphs/contributors

**Comment by aantonop** [comment]
>
> Brandon, I'm so glad you caught this. Contributors are supposed to do a PR
> against preface and add their own name. Since the book is now at the
> publisher, let's do it manually.


How would you like your name listed? Do you want your GitHub ID? See the
preface and compare, let me know ASAP!

Thanks

**Comment by Arvanaghi** [comment]
Spoke with @aantonop on Twitter. Thanks for fixing!
