### ISSUE TITLE
Embark as another very interesting framework for Smartcontracts

### ISSUE THREAD

**Issue by fjrojasgarcia** [ethereumbook/ethereumbook#82]
I'm testing Embark and it's surprising me a lot.
I'm using it with Parity on Kovan and it run like a charm.
I think that the book could have a chapter for the most used frameworks and Embark is one of them.

**Comment by aantonop** [comment]
Link to embark?

**Comment by fjrojasgarcia** [comment]
**Github link**; https://github.com/iurimatias/embark-framework
**Read the docs link**; https://embark.readthedocs.io/en/2.6.4/
**npm packages repository link**; https://www.npmjs.com/package/embark

**Comment by aantonop** [comment]
Added to Frameworks in dev-tools.asciidoc ethereumbook@44304f8
