### ISSUE TITLE
Testnet networks alternatives

### ISSUE THREAD

**Issue by fjrojasgarcia** [ethereumbook/ethereumbook#83]
When a developer comes to Solidity, She or He should know the testnet networks that are out there, Ropsten, Kovan, Rinkeyby, their most important differences, known problems and risks, and important concepts as Proof of Authority, etc.

Let's give a path election to the newcomers.

**Comment by stefek99** [comment]
My thinking - default `testnet` is `ropsten`

Quite literally you do `geth --testnet` and it defaults to `ropsten`

### More options:

* `TestRPC` that became: https://github.com/trufflesuite/ganache-cli
* private blockchain, Microsoft Azure allows one-click deploy
* JavaScript VM - using https://remix.ethereum.org/ you can deploy to a VM without running any software on your machine

---

Kovan, Rinkeby - yeah, worth mentioning too.

**Comment by aantonop** [comment]
Added to ethereum-testnets.asciidoc ethereumbook@deeee44

**Comment by jaycenhorton** [comment]
I just submitted a PR filling in some of this info for GCP using puppeth https://github.com/ethereumbook/ethereumbook/pull/220
