### ISSUE TITLE
Gateways and others forms to access the Ethereum network without local nodes

### ISSUE THREAD

**Issue by fjrojasgarcia** [ethereumbook/ethereumbook#84]
For those who can't spend many resources to maintain synchronized local nodes, I think the book could cover this part also.

There are alternatives to facilitate the use of the Ethereum network without the hassle of maintain synchronized local nodes.

I have personally tested;

- https://infura.io
- https://www.blockcypher.com/dev/ethereum
- https://metamask.io
- https://www.myetherwallet.com

**Comment by aantonop** [comment]
Added section to [clients.asciidoc](https://github.com/ethereumbook/ethereumbook/blob/develop/clients.asciidoc#light-clients-and-rpc-gateways)
