### ISSUE TITLE
Private Ethereum networks creation and maintenance

### ISSUE THREAD

**Issue by fjrojasgarcia** [ethereumbook/ethereumbook#86]
Another aspect probably of interesting application could be the creation of private Ethereum networks and maintenance, p.e. mining considerations.

Although it could be out from the original philosophy of public application of the protocol, it can be very useful in certain circumstances more typical of the business environment.

It would be remarkable the case of https://monax.io

**Comment by stefek99** [comment]
**RELATED**

I'm not Microsoft sales rep or anything, just saw someone on a tutorial video using one click deploy to Azure.

This is the source I believe: https://github.com/Azure/azure-quickstart-templates/tree/master/go-ethereum-on-ubuntu

**Comment by aantonop** [comment]
Private blockchains are probably out of scope. However, deployment of private chains for testing purposes (testRPC, Azure, AWS etc) are definitely in scope.

**Comment by fjrojasgarcia** [comment]
Thinking twice, private blockchains are more an anecdote of the cryptoland so in many cases should be avoided.

Thank you for keeping your best principles firm Andreas.
