### ISSUE TITLE
Can I do Chinese transalation for this book?

### ISSUE THREAD

**Issue by rusher-R** [ethereumbook/ethereumbook#878]
I'm a  soft developer from chinese, I just buy the book in Amazon. Can I freely do translating work for this book in my part time? There is a chinese edition in 'Mastering Bitcoin' book.

**Comment by aantonop** [comment]
Sorry, no. The license does not permit publishing of translations
(derivatives). There is a Chinese publisher already producing a Chinese
translation for sale in China.

One year after publication, we will change the license to permit volunteer
translations.

>

**Comment by linshizai** [comment]
Thank you for your reply. In Decemeber 2019, can I start the transaltion of this book?

**Comment by rusher-R** [comment]
> Sorry, no. The license does not permit publishing of translations (derivatives). There is a Chinese publisher already producing a Chinese translation for sale in China. One year after publication, we will change the license to permit volunteer translations.
> […](#)

Thank you for your reply. In Decemeber 2019, can I start the transaltion of this book?

**Comment by aantonop** [comment]
When the license changes. It will likely be Dec 2019, but is not a fixed
date. I have to get an amended license approved by the publisher at that
time.

File in an issue in Dec 2019 if it hasn't happened yet.

>

**Comment by rusher-R** [comment]
Thanks a lot!
