### ISSUE TITLE
Website Down

### ISSUE THREAD

**Issue by ronaldpetty** [ethereumbook/ethereumbook#88]
Hello,

It seems the link to the website is broken.  Is this expected?

Regards.

Ron

**Comment by kontrollanten** [comment]
Hi!

 I assume that issue #3 still is relevant. @aantonop It may be an idea to remove the URL 'til the site is live?

**Comment by aantonop** [comment]
Not pushing any changes to the repo for now. When I push some actual book
content the site will be up.

**Comment by ronaldpetty** [comment]
@aantonop Any need of technical reviewer for the new book?  Loved MB, just trying to keep up on thing!  Keep up the good work.

**Comment by aantonop** [comment]
Website up
