### ISSUE TITLE
chapter12-dapp frontend npm install error

### ISSUE THREAD

**Issue by SKKU-Security-Lab** [ethereumbook/ethereumbook#880]
hi 
now I try to Auction Platform Frontend built setup
so I follow the Build Setup notice, but it's not working...
after npm install command conduct,  it shows me error message as below.
--------------------------------------------------------------------------------------------------------------
npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated bfj-node4@5.3.1: Switch to the `bfj` package for fixes and new features!
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm ERR! code ENOGIT
npm ERR! Error while executing:
npm ERR! undefined ls-remote -h -t git://github.com/frozeman/WebSocket-Node.git
npm ERR!
npm ERR! undefined
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2019-02-12T12_31_25_692Z-debug.log
------------------------------------------------------------------------------------------------------------------
please help me...

**Comment by AntonioRossi** [comment]
On macOS I also got problems with npm install.
I solved by using node v.8.15.1 and npm v.6.4.1.
Hope this might help you.

**Comment by wbnns** [comment]
@kimrdb Please check to make sure you first have `git` installed on your machine, and try again.

@AntonioRossi Thank you for trying to help.
