### ISSUE TITLE
Chapter 7: web3.toWei is not valid

### ISSUE THREAD

**Issue by athio92** [ethereumbook/ethereumbook#886]
In chapter 7, on the section where we started truffle in `develop` mode, there is a terminal command as follows:
>`FaucetDeployed.send(web3.toWei(1, "ether")).then(res => { console.log(res.logs[0].event, res.logs[0].args) })`

I tested just now and found out that `web3.toWei(1,"ether")` is not a valid function.
This is the correct one: `web3.utils.toWei("1", "ether")`

**Comment by adrianmcli** [comment]
That was probably written with Web3.js 0.X.0 rather than 1.0.

**Comment by ErHarshal** [comment]
this is the web3 version problem in new version utility functions like toWei and many others have been move to web3.utils
