### ISSUE TITLE
General typos

### ISSUE THREAD

**Issue by dnpotter** [ethereumbook/ethereumbook#887]
Incredibly useful and informative book - thanks for all your efforts.  

Some minor issues:

https://github.com/ethereumbook/ethereumbook/blob/develop/09smart-contracts-security.asciidoc#the-vulnerability-1: end of 3rd para "if we try to subtract 1 from a **uint8** whose value is -128, we will get 127" should be int8

https://github.com/ethereumbook/ethereumbook/blob/develop/09smart-contracts-security.asciidoc#preventative-techniques-10: 2nd para "the require on **line 13**" should be line 5.

https://github.com/ethereumbook/ethereumbook/blob/develop/09smart-contracts-security.asciidoc#preventative-techniques-14: 2nd para `msg.sender/weiPerTokens` should be `msg.value/weiPerTokens`

https://github.com/ethereumbook/ethereumbook/blob/develop/13evm.asciidoc#turing-completeness-and-gas: 1st para typo "...with **an** very important caveat"

**Comment by wbnns** [comment]
@dnpotter Thank you. These issues have all been resolved in preparation for the next upcoming print.
