### ISSUE TITLE
Developer tools

### ISSUE THREAD

**Issue by apmilen** [ethereumbook/ethereumbook#89]
Hi,

I have no idea if you're planning on writing about Ethereum developer tools. If you are, I'd like to draw your attention to https://dapp.tools , a command line toolchain and smart contract standard library written in the style of the Unix design philosophy. However I think you probably shouldn't write about developer tools, as those trends can change very quickly (as we've seen in Javascript).

Looking forward to your book!

**Comment by duaraghav8** [comment]
Hi,
@apmilen does have a valid point, but I'd still be inclined toward mentioning dev tools in the book. Mentioning 2-3 tools for different categories would give newbies a good idea of what all is happening in the dapp space and where all the focus lies.
If you do decide to add dev tools, please consider [Solium](https://github.com/duaraghav8/Solium) - security-focused linter for Solidity contracts. Great ecosystem + integrations around it.
Another tool in the same category is [Solcheck](https://github.com/federicobond/solcheck)

**Comment by fjrojasgarcia** [comment]
I had read something about https://dapp.tools, but in a deeper review I realized that it is a real promise for developers oriented to unix-like tools.

I have the feeling that I'm going to switch to https://dapp.tools.

@apmilen,  thank you very much for your valuable contribution.

**Comment by aantonop** [comment]
I will be adding dapp.tools to the dev-env section

Thanks!
