### ISSUE TITLE
Chapter 1, none of the evm compilers under version0.4.19 sucessfully compile. 

### ISSUE THREAD

**Issue by jimenezfer** [ethereumbook/ethereumbook#893]
New in the eth space, compiling my first contract , but unable to compile, used all 0.4.19 versions.

Any ideas?

Thank you!

**Comment by jgraber-io** [comment]
Having the exact same issue.  Would you mind sharing how you solved this, @jimenezfer ? 🙏

**Comment by JohnGraber** [comment]
Ah.  Never mind.

**Compiling with 0.5.10 works.**

**Comment by jgraber-io** [comment]
**0.4.26 will compile.**

Trial and error, ftw.
