### ISSUE TITLE
It is empty repo

### ISSUE THREAD

**Issue by mikhailrojo** [ethereumbook/ethereumbook#90]
this is quite empty repo with no book

**Comment by stefek99** [comment]
It seems like the only fleshed out chapter: https://github.com/ethereumbook/ethereumbook/blob/develop/dev-env.asciidoc

Seems that is available to pre-order on Amazon: https://www.amazon.com/Mastering-Ethereum-Building-Smart-Contracts/dp/1491971940

What is the status? cc @aantonop

**Comment by aantonop** [comment]
Updated README to reflect current status. Due to ufortunate personal issues, the release has been delayed by 6 months. Expect to see content committed in Q1 and Q2 2018
