### ISSUE TITLE
Ethereum addresses - how are they created - no checksum - EIP with capitalisation

### ISSUE THREAD

**Issue by stefek99** [ethereumbook/ethereumbook#91]
* https://www.royalfork.org/2017/12/10/eth-graphical-address/
* https://ethereum.stackexchange.com/questions/3542/how-are-ethereum-addresses-generated/3619
* https://ethereum.stackexchange.com/questions/267/why-dont-ethereum-addresses-have-checksums
* https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md

**Comment by aantonop** [comment]
Added to "Keys & Addresses" chapter outline ethereumbook@91d7c2e
