### ISSUE TITLE
Would a PR for "next" and "previous" chapters at the footer of the .asciidoc files be accepted?

### ISSUE THREAD

**Issue by technoplato** [ethereumbook/ethereumbook#912]
It's a small thing, but I would find it more convenient to read this in the Repository if you could easily navigate chapters at the bottom of each respective chapter. 

I'd put in a PR if someone would say it would be accepted. 

Thanks.

**Comment by aantonop** [comment]
No, sorry. The primary "target" for the source code is the print edition.

I am preparing to open source the book anyway, so people can start making PDFs for easier reading.

**Comment by technoplato** [comment]
Understood, thanks!
