### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by MariaZM24** [ethereumbook/ethereumbook#92]
Hello,
I'm a translation student and I'm an Ethereum enthusiast. I would like to translate this book to colaborate and also as my thesis translation project.
If you're interested, please send me the text or a link where I can read it and work from.

Thanks!

**Comment by fjrojasgarcia** [comment]
I am also interested in participating in the **Spanish translation** of this book.
I'm a Blockchain Engineer with experience in translation of documentation and literature related to the crypto space.

**Comment by aantonop** [comment]
The book is published by O'Reilly Media. Volunteer translations can only happen after it has switched to a license that allows derivatives, which may be 6 months *after* publication. Depending on demand, we may have a Spanish publisher ask to license it before then. Translations are completely outside my control for the first 6 months.

**Comment by asanzdiego** [comment]
Hello,
I am also interested in participating in the Spanish translation of this book.
I am a Software Engineer with experience in DApp development with Ethrerum.
When the license changes to one that allows derivatives, please tell us so we can coordinate.
Thanks
