### ISSUE TITLE
Metamask

### ISSUE THREAD

**Issue by fjrojasgarcia** [ethereumbook/ethereumbook#93]
I think it would be of great interest to pay attention to the **Metamask** tool, for the utility it provides, also in the particular case of the **Dapps's end users** with which they can, **identify themselves** in Dapps and **perform financial operations** using this plugin integrated into the browser.

Website; https://metamask.io/

**Comment by aantonop** [comment]
I already have MetaMask included in the "clients" section. The use as a Dapp browser will be covered in some part too.
