### ISSUE TITLE
OpenZeppelin - open framework of reusable and secure smart contracts

### ISSUE THREAD

**Issue by fjrojasgarcia** [ethereumbook/ethereumbook#94]
It worth mentioning **OpenZeppelin** which is an open framework of **reusable and secure** smart contracts in the Solidity language.

**Github link**; https://github.com/OpenZeppelin
**Website link**; https://openzeppelin.org/
**Read the docs link**; http://zeppelin-solidity.readthedocs.io/en/latest/index.html

**Comment by aantonop** [comment]
Very much interested in adding OpenZeppelin. It will fit under "Frameworks", which might end up being a whole chapter

**Comment by aantonop** [comment]
Added ethereumbook/ethereumbook@ffbdbec
