### ISSUE TITLE
Smart contracts versioning - Effects of the immutability of the Blockchain in the development cycle

### ISSUE THREAD

**Issue by fjrojasgarcia** [ethereumbook/ethereumbook#95]
I think It is a matter of importance for the new developers of Ethereum to know the implications of the immutability of the blockchain in the development of their projects.

In this development platform, the publication of a Smart contract becomes an immutable action which differs from any other typical development cycle, where one always has the possibility to modify the previous behavior, in what is called a system of versioned.

**Comment by aantonop** [comment]
Noted!

"Immutability and how it affects development, deployment and testing". Will fit somewhere

**Comment by barrymac** [comment]
Leading to workarounds such as what may be partially responsible for the infamous wallet hack. Testing,  testing, testing .  Will there be a chapter on testing with truffle?
