### ISSUE TITLE
Ethereum Package Registry

### ISSUE THREAD

**Issue by fjrojasgarcia** [ethereumbook/ethereumbook#96]
Perhaps it would not hurt to inform the new developers who will use Solidity about the existence of **repositories of reusable / sharable packages**.
I believe that this can enhance the open source concept applied to the development of solutions based on Solidity.

**Github link**; https://github.com/ethpm
**Repository link**; https://www.ethpm.com/registry
**Website**; https://www.ethpm.com/
**Documentation**; https://www.ethpm.com/docs/integration-guide

**Comment by aantonop** [comment]
Agreed and noted

**Comment by aantonop** [comment]
Added to best practices section in smart contracts outline ethereumbook/ethereumbook@47646f0
