### ISSUE TITLE
Typos in smart contract and tokens chapter

### ISSUE THREAD

**Issue by alko89** [ethereumbook/ethereumbook#964]
Hi

While reading the book I noticed a two typos in 9th and 10th chapter:

The first one is in chapter 9 line 1107 in the contract comment, that is missing a space (`transactionsas`). I'm not sure if this is intended because the referenced contract had the typo as well.

The second one in chapter 10 line 702 its written `transfer tokens defined in another token.` I think this should be `transfer tokens defined in another contract.`.

I can create a PR with a fix.

**Comment by 0xmountaintop** [comment]
@Alko89 sure you are welcome to do so. It is indeed a typo.
