### ISSUE TITLE
Tokens (ERC20)

### ISSUE THREAD

**Issue by apmilen** [ethereumbook/ethereumbook#97]
You should write about how to treat Ether as an ERC20 token using the standard wrapper contract:

https://etherscan.io/address/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2

**Comment by fjrojasgarcia** [comment]
Sure. You can also point to https://theethereum.wiki/w/index.php/ERC20_Token_Standard

**Comment by aantonop** [comment]
ERC20 and subsequent standards (ERC223) are going to get a big section. Definitely!

**Comment by aantonop** [comment]
Added tokens.asciidoc ethereumbook/ethereumbook@cd43007
