### ISSUE TITLE
Error getting Ether from faucet in Ropsten

### ISSUE THREAD

**Issue by adrisys** [ethereumbook/ethereumbook#973]
When I try to request 1 ether from faucet in Ropsten network I get:

```{"error":"[ethjs-query] while formatting outputs from RPC '{\"value\":{\"code\":-32603,\"message\":\"Too Many Requests\",\"data\":{\"originalError\":{}},\"stack\":\"Error: Too Many Requests\\n at /www/node_modules/web3-provider-engine/subproviders/rpc.js:51:23\\n at Request._callback (/www/node_modules/web3-provider-engine/subproviders/rpc.js:53:11)\\n at Request.self.callback (/www/node_modules/request/request.js:185:22)\\n at Request.emit (events.js:310:20)\\n at Request.<anonymous> (/www/node_modules/request/request.js:1154:10)\\n at Request.emit (events.js:310:20)\\n at IncomingMessage.<anonymous> (/www/node_modules/request/request.js:1076:12)\\n at Object.onceWrapper (events.js:416:28)\\n at IncomingMessage.emit (events.js:322:22)\\n at endReadableNT (_stream_readable.js:1187:12)\"}}'"}```

I tried in Chrome and Firefox.

**Comment by jordanlesich** [comment]
I also got this error last night. After switching networks, opening and closing my browser, signing in and out of metaMask, and waiting, it ended up working.
