### ISSUE TITLE
Ethereum Smart Contract Security Best Practices

### ISSUE THREAD

**Issue by fjrojasgarcia** [ethereumbook/ethereumbook#98]
In my opinion it would be necessary to devote enough space in the book to deal with the issue of the **Security of Smart Contracts**.

In this sense there are already initiatives focused on this important aspect of the development of Smart Contracts such as maintained by ConsenSys Diligence, and the broader Ethereum community, thinking in the intermediate Solidity programmers.

Link(s);
Github: https://github.com/ConsenSys/smart-contract-best-practices/
Docs: https://consensys.github.io/smart-contract-best-practices/

**Comment by aantonop** [comment]
Agreed. OpenZeppelin has also published some security guidelines

**Comment by aantonop** [comment]
Added to Smart Contracts outline  ethereumbook/ethereumbook@79d608b
