### ISSUE TITLE
Book code examples in Solidity v0.6.12 and showcase scripts for Truffle projects

### ISSUE THREAD

**Issue by vnavascues** [ethereumbook/ethereumbook#989]
Hello everyone,

First of all, I'd like to thank you the authors and contributors of this book.

I've been following the code examples, so I want to share my work in case it can help anyone. Besides comments and my own twist, these are the main differences from the book:

- Written in Solidity v0.6.12 and documented using NatSpec.

- Each Truffle project has showcase scripts.

- **Chapter 09 - Smart Contracts Security**: only the reentrancy attack has been implemented (along with a test suite).

- **Chapter 11 - Oracles**: used Chainlink instead of Provable (Oraclize).

- Chapters 08 (Vyper), 12 (dApp) and 13 (EVM) not included.

https://github.com/vnavascues/solidity_playground

Feedback welcome. Thanks again,

vnavascues

**Comment by wbnns** [comment]
@vnavascues

Thanks for sharing. 👍 The code in the book is in the process of being updated, so stay tuned for more opportunities to work through additional material.
