### ISSUE TITLE
Swarm - Serverless Hosting storage and content distribution

### ISSUE THREAD

**Issue by fjrojasgarcia** [ethereumbook/ethereumbook#99]
**Swarm** is a native base layer service of the ethereum web3 stack intended as a **Serverless Hosting** incentivised peer-to-peer storage and content distribution, something that I think the average Ethereum programmer should know about.

The primary objective of Swarm is to provide a **decentralized and redundant store for dapp code and data** as well as block chain and state data. Swarm is also set out to provide various base layer services for web3, including node-to-node messaging, media streaming, decentralised database services and scalable state-channel infrastructure for decentralised service economies.

Link(s)
**Swarm home page**; http://swarm-gateways.net/bzz:/theswarm.eth/
**Read the docs**; https://swarm-guide.readthedocs.io/en/latest/index.html
**Swarm developer's onboarding guide**; https://github.com/ethersphere/swarm/wiki/swarm
**The swarm engine room**; https://gitter.im/ethersphere/orange-lounge
**Similarities/differences between Ethereum's Swarm and IPFS**; https://github.com/ethersphere/go-ethereum/wiki/IPFS-&-SWARM

**Comment by aantonop** [comment]
Added to Dapp chapter outline ethereumbook@9154691
