### ISSUE TITLE
Link to Truffle section in chapter 07 is incorrect

### ISSUE THREAD

**Issue by noconsulate** [ethereumbook/ethereumbook#990]
The link to setting up Truffle in Chapter 07 seems to look for the Truffle section within Chapter 7 but that section is actually in the appendix.

**Comment by wbnns** [comment]
Hello, apologies, I'm unable to reproduce this issue. Please let me know the steps you took to encounter it on your side and I'll reopen to investigate.

**Comment by liubq7** [comment]
Yes, it should be https://github.com/ethereumbook/ethereumbook/blob/05f0dfe6c41635ac85527a60c06ac5389d8006e7/appdx-dev-tools.asciidoc#truffle
