### ISSUE TITLE
Ch8: The URL of Vyper Example failed

### ISSUE THREAD

**Issue by howardpen9** [ethereumbook/ethereumbook#992]
https://github.com/ethereumbook/ethereumbook/blob/develop/08smart-contracts-vyper.asciidoc

![image](https://user-images.githubusercontent.com/36764495/92537411-a2ceaf00-f26e-11ea-9784-1798ea579bab.png)

LINK: https://github.com/vyperlang/vyper/blob/master/vyper/types/convert.py 
can't be found.

**Comment by howardpen9** [comment]
should be changed to this link

https://github.com/vyperlang/vyper/blob/da740d968f2562693fd576790b7b3f0441864a91/vyper/functions/convert.py

**Comment by wbnns** [comment]
@howardpen9 Thanks!
