### ISSUE TITLE
Suggestion : PDF version of the book

### ISSUE THREAD

**Issue by dazdaz** [ethereumbook/ethereumbook#993]
How about either providing a PDF or instructions on howto create a PDF from this content.

**Comment by aantonop** [comment]
While this content is provided for free and under an open license, convenience costs money...

Producing a quality PDF from the source requires quite a lot of work to set up. I sell an ebook bundle, that you can read on a variety of devices with well formatted PDF, EPUB and MOBI files on my website (aantonop.com/shop)
