### ISSUE TITLE
Alchemy Contributions - appdx-dev-tools.asciidoc

### ISSUE THREAD

**Issue by deric-alchemy** [ethereumbook/ethereumbook#997]
@aantonop Please take a look and let us know if this outline for changes below seems reasonable - if so, we'll go ahead and write it up.

We (engineers from Alchemy) plan on modifying [appdx-web3js-tutorial.asciidoc](https://github.com/ethereumbook/ethereumbook/blob/develop/appdx-web3js-tutorial.asciidoc) to include references to both Infura and Alchemy, so that potential developers have clarity on available options in the node infrastructure provider space.

We also plan on contributing a section with the following outline to [appdx-dev-tools.asciidoc](https://github.com/ethereumbook/ethereumbook/blob/develop/appdx-dev-tools.asciidoc).

### Alchemy API

Website: [https://alchemyapi.io](https://alchemyapi.io)

Alchemy API is a node infrastructure provider that maintains nodes as cloud services and executes node requests for you. It serves access to regularly updated Geth and Parity nodes that guarantee reliability, data correctness and scalability.

It also provides additional developer tools such as: 

##### API Explorer
Browser tool allowing you to search and analyze all your API requests to track patterns, find errors, and simplify debugging.

##### Mempool Visualizer
Allows you to view and search for mined, pending, and dropped transactions in an Alchemy-hosted mempool, so you can track the status of your transactions.

##### Composer
Allows you to create test API requests using a simplified online UX instead of the command line.

##### Notify
Uses Webhooks to allow you access to notifications whenever you see activity on a particular Ethereum address, have transactions in your mempool mined or dropped, or when Ethereum gas prices drop below a certain amount.

#### Setup 
Instructions on how to setup Alchemy API.

**Comment by aantonop** [comment]
This looks great. I think you might want to add a section in the beginning that explains "why and when should I use Alchemy", to help create context and relevance. 

Otherwise, please proceed. I will gladly accept a PR for these two sections. Please also remember to add the names of the contributors directly to the github contributors document as part of the PR. You can add as a "team" or mix in alphabetically with the rest.

**Comment by wbnns** [comment]
PRs merged.
